#!/usr/bin/env php
<?php

require_once 'bootstrap.php';

use Phixtures\DIContainer;

$DIConfig = array(
	'database' => array(
		'user' => 'root',
		'password' => '',
		'target_schema' => 'dev',
	),
);

$container = new DIContainer($DIConfig);
$application = $container['application'];
$application->run();
